This yml file is not up-to-date with instruction given on README. - repo link for diff-gaussian-rasterization-w-depth was not working using yml.
I also added a line to set the corresponding gcc&g++ version.
The reason here is because I was using gcc14 and according to https://gist.github.com/ax3l/9489132 CUDA 11.6 doesn't support gcc and g++ greater than certain versions.

```
D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      cuda_rasterizer/auxiliary.h(151): warning #177-D: variable "p_proj" was declared but never referenced

      /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |                                                                                                                                                 ^
      /usr/include/c++
```